export const PARITY_B_COPY = Object.freeze({
  en: {
    subtitle: 'IN REAL TIME',
    livePrefix: 'Global military spending is',
    liveSuffix: 'every second.',
    lead: 'Armed conflicts carry large-scale, long-term consequences. Trillions of dollars are diverted from global development. The opportunity cost includes unrealised infrastructure, undiscovered treatments and unresolved humanitarian crises.',
    mainCaption: 'These resources are redirected from global development towards military infrastructure.',
    sessionTitle: 'DURING YOUR VIEW OF THIS PAGE:',
    sessionNote: 'allocated to global military budgets.',
    sessionAlternatives: 'Alternative allocation of these resources could:',
    food: 'provide food for',
    health: 'provide basic healthcare for',
    poverty: 'lift from extreme poverty',
    people: 'people',
    personalBurden: 'INDIRECT FINANCIAL BURDEN',
    personalBurdenDesc: 'Average indirect financial burden per person on the planet.',
    economicTitle: 'ECONOMIC IMPACT',
    economicIntro: 'Military expenditure is only one part of the total cost. Conflict also destroys infrastructure, reduces productive life-years and creates wider economic losses.',
    directDeaths: 'DIRECT DEMOGRAPHIC LOSSES',
    indirectDeaths: 'INDIRECT DEMOGRAPHIC LOSSES',
    infrastructure: 'INFRASTRUCTURE DAMAGE',
    lifeYears: 'YEARS OF LIFE LOST',
    economicLoss: 'TOTAL ECONOMIC IMPACT',
    opportunityTitle: 'WHAT THE SAME RESOURCES COULD SUPPORT',
    opportunityIntro: 'Move the share to see how a fraction of military expenditure compares with major global development needs.',
    programmes: [
      ['education', 'Universal basic education'],
      ['hunger', 'Ending global hunger'],
      ['health', 'Universal health coverage'],
      ['water', 'Clean water and sanitation'],
      ['electricity', 'Universal electricity access'],
      ['internet', 'Universal internet access'],
      ['climate', 'Climate finance'],
      ['schools', 'Schools and educational facilities'],
    ],
    times: '×',
    institutions: 'institutions',
  },
  ru: {
    subtitle: 'В РЕАЛЬНОМ ВРЕМЕНИ',
    livePrefix: 'Глобальные оборонные расходы составляют',
    liveSuffix: 'каждую секунду.',
    lead: 'Вооруженные конфликты влекут за собой масштабные долгосрочные последствия. Это триллионы долларов, отвлеченные от программ глобального развития. Альтернативная стоимость этих средств включает нереализованные инфраструктурные проекты, неоткрытые методы лечения и нерешенные гуманитарные кризисы.',
    mainCaption: 'Данные ресурсы перенаправляются из глобального бюджета развития на финансирование военной инфраструктуры.',
    sessionTitle: 'ЗА ВРЕМЯ ПРОСМОТРА ДАННОЙ СТРАНИЦЫ:',
    sessionNote: 'выделено на глобальные оборонные бюджеты.',
    sessionAlternatives: 'Альтернативное распределение данных средств позволило бы:',
    food: 'обеспечить продовольствием',
    health: 'предоставить базовые медуслуги',
    poverty: 'вывести из крайней нищеты',
    people: 'человек',
    personalBurden: 'КОСВЕННОЕ ФИНАНСОВОЕ БРЕМЯ',
    personalBurdenDesc: 'Усредненная косвенная финансовая нагрузка на каждого жителя планеты.',
    economicTitle: 'ЭКОНОМИЧЕСКИЕ ПОСЛЕДСТВИЯ',
    economicIntro: 'Военные расходы — лишь часть общей цены. Вооруженные конфликты также разрушают инфраструктуру, сокращают годы полноценной жизни и создают более широкий экономический ущерб.',
    directDeaths: 'ПРЯМЫЕ ДЕМОГРАФИЧЕСКИЕ ПОТЕРИ',
    indirectDeaths: 'КОСВЕННЫЕ ДЕМОГРАФИЧЕСКИЕ ПОТЕРИ',
    infrastructure: 'УЩЕРБ ИНФРАСТРУКТУРЕ',
    lifeYears: 'ПОТЕРЯННЫЕ ГОДЫ ЖИЗНИ',
    economicLoss: 'СОВОКУПНЫЙ ЭКОНОМИЧЕСКИЙ УЩЕРБ',
    opportunityTitle: 'ЧТО МОГЛИ БЫ ПОДДЕРЖАТЬ ТЕ ЖЕ РЕСУРСЫ',
    opportunityIntro: 'Изменяйте долю, чтобы сравнить часть военных расходов с масштабом ключевых глобальных потребностей развития.',
    programmes: [
      ['education', 'Универсальное базовое образование'],
      ['hunger', 'Ликвидация глобального голода'],
      ['health', 'Универсальный охват услугами здравоохранения'],
      ['water', 'Обеспечение чистой водой и санитарией'],
      ['electricity', 'Всеобщий доступ к электричеству'],
      ['internet', 'Всеобщий доступ к интернету'],
      ['climate', 'Климатическое финансирование'],
      ['schools', 'Школы и образовательные учреждения'],
    ],
    times: 'раз',
    institutions: 'учреждений',
  },
});

export function parityCopy(language) {
  return PARITY_B_COPY[language] || PARITY_B_COPY.en;
}
